version: "3"

services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    environment:
      - SECRET_AUTH_KEY
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:                   
        - net_admin
        - sys_module
    command: tailscaled
    privileged: true
    network_mode: "host"
    restart: unless-stopped
